//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.06.21 at 11:42:50 PM CEST
//

package de.uni_due.s3.openmath;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openmath.org/OpenMath}OMS"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;group ref="{http://www.openmath.org/OpenMath}omel"/>
 *           &lt;element ref="{http://www.openmath.org/OpenMath}OMFOREIGN"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.openmath.org/OpenMath}common.attributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"oms", "omsOrOMVOrOMI"})
@XmlRootElement(name = "OME")
public class OME {

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element ref="{http://www.openmath.org/OpenMath}OMATP"/>
   *         &lt;group ref="{http://www.openmath.org/OpenMath}omel"/>
   *       &lt;/sequence>
   *       &lt;attGroup ref="{http://www.openmath.org/OpenMath}compound.attributes"/>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"omatp", "oms", "omv", "omi", "omb", "omstr", "omf", "oma",
      "ombind", "ome", "omattr", "omr"})
  public static class OMATTR {

    @XmlElement(name = "OMATP", required = true)
    protected OMATP omatp;
    @XmlElement(name = "OMS")
    protected OMS oms;
    @XmlElement(name = "OMV")
    protected OMV omv;
    @XmlElement(name = "OMI")
    protected OMI omi;
    @XmlElement(name = "OMB")
    protected OMB omb;
    @XmlElement(name = "OMSTR")
    protected OMSTR omstr;
    @XmlElement(name = "OMF")
    protected OMF omf;
    @XmlElement(name = "OMA")
    protected OMA oma;
    @XmlElement(name = "OMBIND")
    protected OMBIND ombind;
    @XmlElement(name = "OME")
    protected OME ome;
    @XmlElement(name = "OMATTR")
    protected OME.OMATTR omattr;
    @XmlElement(name = "OMR")
    protected OMR omr;
    @XmlAttribute(name = "cdbase")
    @XmlSchemaType(name = "anyURI")
    protected String cdbase;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the cdbase property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCdbase() {
      return cdbase;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
      return id;
    }

    /**
     * Gets the value of the oma property.
     * 
     * @return possible object is {@link OMA }
     * 
     */
    public OMA getOMA() {
      return oma;
    }

    /**
     * Gets the value of the omatp property.
     * 
     * @return possible object is {@link OMATP }
     * 
     */
    public OMATP getOMATP() {
      return omatp;
    }

    /**
     * Gets the value of the omattr property.
     * 
     * @return possible object is {@link OME.OMATTR }
     * 
     */
    public OME.OMATTR getOMATTR() {
      return omattr;
    }

    /**
     * Gets the value of the omb property.
     * 
     * @return possible object is {@link OMB }
     * 
     */
    public OMB getOMB() {
      return omb;
    }

    /**
     * Gets the value of the ombind property.
     * 
     * @return possible object is {@link OMBIND }
     * 
     */
    public OMBIND getOMBIND() {
      return ombind;
    }

    /**
     * Gets the value of the ome property.
     * 
     * @return possible object is {@link OME }
     * 
     */
    public OME getOME() {
      return ome;
    }

    /**
     * Gets the value of the omf property.
     * 
     * @return possible object is {@link OMF }
     * 
     */
    public OMF getOMF() {
      return omf;
    }

    /**
     * Gets the value of the omi property.
     * 
     * @return possible object is {@link OMI }
     * 
     */
    public OMI getOMI() {
      return omi;
    }

    /**
     * Gets the value of the omr property.
     * 
     * @return possible object is {@link OMR }
     * 
     */
    public OMR getOMR() {
      return omr;
    }

    /**
     * Gets the value of the oms property.
     * 
     * @return possible object is {@link OMS }
     * 
     */
    public OMS getOMS() {
      return oms;
    }

    /**
     * Gets the value of the omstr property.
     * 
     * @return possible object is {@link OMSTR }
     * 
     */
    public OMSTR getOMSTR() {
      return omstr;
    }

    /**
     * Gets the value of the omv property.
     * 
     * @return possible object is {@link OMV }
     * 
     */
    public OMV getOMV() {
      return omv;
    }

    /**
     * Sets the value of the cdbase property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCdbase(String value) {
      this.cdbase = value;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setId(String value) {
      this.id = value;
    }

    /**
     * Sets the value of the oma property.
     * 
     * @param value allowed object is {@link OMA }
     * 
     */
    public void setOMA(OMA value) {
      this.oma = value;
    }

    /**
     * Sets the value of the omatp property.
     * 
     * @param value allowed object is {@link OMATP }
     * 
     */
    public void setOMATP(OMATP value) {
      this.omatp = value;
    }

    /**
     * Sets the value of the omattr property.
     * 
     * @param value allowed object is {@link OME.OMATTR }
     * 
     */
    public void setOMATTR(OME.OMATTR value) {
      this.omattr = value;
    }

    /**
     * Sets the value of the omb property.
     * 
     * @param value allowed object is {@link OMB }
     * 
     */
    public void setOMB(OMB value) {
      this.omb = value;
    }

    /**
     * Sets the value of the ombind property.
     * 
     * @param value allowed object is {@link OMBIND }
     * 
     */
    public void setOMBIND(OMBIND value) {
      this.ombind = value;
    }

    /**
     * Sets the value of the ome property.
     * 
     * @param value allowed object is {@link OME }
     * 
     */
    public void setOME(OME value) {
      this.ome = value;
    }

    /**
     * Sets the value of the omf property.
     * 
     * @param value allowed object is {@link OMF }
     * 
     */
    public void setOMF(OMF value) {
      this.omf = value;
    }

    /**
     * Sets the value of the omi property.
     * 
     * @param value allowed object is {@link OMI }
     * 
     */
    public void setOMI(OMI value) {
      this.omi = value;
    }

    /**
     * Sets the value of the omr property.
     * 
     * @param value allowed object is {@link OMR }
     * 
     */
    public void setOMR(OMR value) {
      this.omr = value;
    }

    /**
     * Sets the value of the oms property.
     * 
     * @param value allowed object is {@link OMS }
     * 
     */
    public void setOMS(OMS value) {
      this.oms = value;
    }

    /**
     * Sets the value of the omstr property.
     * 
     * @param value allowed object is {@link OMSTR }
     * 
     */
    public void setOMSTR(OMSTR value) {
      this.omstr = value;
    }

    /**
     * Sets the value of the omv property.
     * 
     * @param value allowed object is {@link OMV }
     * 
     */
    public void setOMV(OMV value) {
      this.omv = value;
    }

  }

  @XmlElement(name = "OMS", required = true)
  protected OMS oms;
  @XmlElements({@XmlElement(name = "OMS", type = OMS.class),
      @XmlElement(name = "OMV", type = OMV.class), @XmlElement(name = "OMI", type = OMI.class),
      @XmlElement(name = "OMB", type = OMB.class), @XmlElement(name = "OMSTR", type = OMSTR.class),
      @XmlElement(name = "OMF", type = OMF.class), @XmlElement(name = "OMA", type = OMA.class),
      @XmlElement(name = "OMBIND", type = OMBIND.class),
      @XmlElement(name = "OME", type = OME.class),
      @XmlElement(name = "OMATTR", type = OME.OMATTR.class),
      @XmlElement(name = "OMR", type = OMR.class),
      @XmlElement(name = "OMFOREIGN", type = OMFOREIGN.class)})
  protected List<Object> omsOrOMVOrOMI;

  @XmlAttribute(name = "id")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId() {
    return id;
  }

  /**
   * Gets the value of the oms property.
   * 
   * @return possible object is {@link OMS }
   * 
   */
  public OMS getOMS() {
    return oms;
  }

  /**
   * Gets the value of the omsOrOMVOrOMI property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the omsOrOMVOrOMI property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getOMSOrOMVOrOMI().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link OMS } {@link OMV } {@link OMI }
   * {@link OMB } {@link OMSTR } {@link OMF } {@link OMA } {@link OMBIND } {@link OME }
   * {@link OME.OMATTR } {@link OMR } {@link OMFOREIGN }
   * 
   * 
   */
  public List<Object> getOMSOrOMVOrOMI() {
    if (omsOrOMVOrOMI == null) {
      omsOrOMVOrOMI = new ArrayList<Object>();
    }
    return this.omsOrOMVOrOMI;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Sets the value of the oms property.
   * 
   * @param value allowed object is {@link OMS }
   * 
   */
  public void setOMS(OMS value) {
    this.oms = value;
  }

}
