image: maven:3-jdk-8

build:
  script: "mvn install -B;curl -u s3gitlab:$ARTIFACTORY_KEY -X PUT \"https://harbor.paluno.uni-due.de/artifactory/libs-release-local/de/uni_due/s3/Evaluator/2.0.0/Evaluator-2.0.0new.jar\" -T \"/root/.m2/repository/de/uni_due/s3/Evaluator/2.0.0/Evaluator-2.0.0.jar\""