//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.06.21 at 11:42:50 PM CEST
//

package de.uni_due.s3.JAXBOpenMath.openmath;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.openmath.org/OpenMath}omel"/>
 *         &lt;element ref="{http://www.openmath.org/OpenMath}OMBVAR"/>
 *         &lt;group ref="{http://www.openmath.org/OpenMath}omel"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.openmath.org/OpenMath}compound.attributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"content"})
@XmlRootElement(name = "OMBIND")
public class OMBIND {

  @XmlElementRefs({
      @XmlElementRef(name = "OMATTR", namespace = "http://www.openmath.org/OpenMath",
          type = JAXBElement.class),
      @XmlElementRef(name = "OMBIND", namespace = "http://www.openmath.org/OpenMath",
          type = OMBIND.class),
      @XmlElementRef(name = "OMF", namespace = "http://www.openmath.org/OpenMath",
          type = OMF.class),
      @XmlElementRef(name = "OMBVAR", namespace = "http://www.openmath.org/OpenMath",
          type = OMBVAR.class),
      @XmlElementRef(name = "OME", namespace = "http://www.openmath.org/OpenMath",
          type = OME.class),
      @XmlElementRef(name = "OMA", namespace = "http://www.openmath.org/OpenMath",
          type = OMA.class),
      @XmlElementRef(name = "OMV", namespace = "http://www.openmath.org/OpenMath",
          type = OMV.class),
      @XmlElementRef(name = "OMSTR", namespace = "http://www.openmath.org/OpenMath",
          type = OMSTR.class),
      @XmlElementRef(name = "OMB", namespace = "http://www.openmath.org/OpenMath",
          type = OMB.class),
      @XmlElementRef(name = "OMS", namespace = "http://www.openmath.org/OpenMath",
          type = OMS.class),
      @XmlElementRef(name = "OMR", namespace = "http://www.openmath.org/OpenMath",
          type = OMR.class),
      @XmlElementRef(name = "OMI", namespace = "http://www.openmath.org/OpenMath",
          type = OMI.class)})
  protected List<Object> content;
  @XmlAttribute(name = "cdbase")
  @XmlSchemaType(name = "anyURI")
  protected String cdbase;
  @XmlAttribute(name = "id")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;

  /**
   * Gets the value of the cdbase property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCdbase() {
    return cdbase;
  }

  /**
   * Gets the rest of the content model.
   * 
   * <p>
   * You are getting this "catch-all" property because of the following reason: The field name "OMS"
   * is used by two different parts of a schema. See: line 15 of
   * file:/home/daniel/workspace/de.uni_due.s3.jack2.server.core.util. evaluator/jaxb/openmath2.xsd
   * line 15 of file:/home/daniel/workspace/de.uni_due.s3.jack2.server.core.util.
   * evaluator/jaxb/openmath2.xsd
   * <p>
   * To get rid of this property, apply a property customization to one of both of the following
   * declarations to change their names: Gets the value of the content property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the content property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getContent().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link OMF } {@link OMBIND }
   * {@link JAXBElement }{@code <}{@link OME.OMATTR }{@code >} {@link OMBVAR } {@link OMA }
   * {@link OME } {@link OMV } {@link OMS } {@link OMB } {@link OMSTR } {@link OMI } {@link OMR }
   * 
   * 
   */
  public List<Object> getContent() {
    if (content == null) {
      content = new ArrayList<Object>();
    }
    return this.content;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the cdbase property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCdbase(String value) {
    this.cdbase = value;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setId(String value) {
    this.id = value;
  }

}
