//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.06.21 at 11:42:50 PM CEST
//

package de.uni_due.s3.JAXBOpenMath.openmath;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.openmath.org/OpenMath}omel"/>
 *       &lt;attGroup ref="{http://www.openmath.org/OpenMath}compound.attributes"/>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"oms", "omv", "omi", "omb", "omstr", "omf", "oma", "ombind", "ome",
    "omattr", "omr"})
@XmlRootElement(name = "OMOBJ")
public class OMOBJ {

  @XmlElement(name = "OMS")
  protected OMS oms;
  @XmlElement(name = "OMV")
  protected OMV omv;
  @XmlElement(name = "OMI")
  protected OMI omi;
  @XmlElement(name = "OMB")
  protected OMB omb;
  @XmlElement(name = "OMSTR")
  protected OMSTR omstr;
  @XmlElement(name = "OMF")
  protected OMF omf;
  @XmlElement(name = "OMA")
  protected OMA oma;
  @XmlElement(name = "OMBIND")
  protected OMBIND ombind;
  @XmlElement(name = "OME")
  protected OME ome;
  @XmlElement(name = "OMATTR")
  protected OME.OMATTR omattr;
  @XmlElement(name = "OMR")
  protected OMR omr;
  @XmlAttribute(name = "version")
  protected String version;
  @XmlAttribute(name = "cdbase")
  @XmlSchemaType(name = "anyURI")
  protected String cdbase;
  @XmlAttribute(name = "id")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;

  /**
   * Gets the value of the cdbase property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCdbase() {
    return cdbase;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId() {
    return id;
  }

  /**
   * Gets the value of the oma property.
   * 
   * @return possible object is {@link OMA }
   * 
   */
  public OMA getOMA() {
    return oma;
  }

  /**
   * Gets the value of the omattr property.
   * 
   * @return possible object is {@link OME.OMATTR }
   * 
   */
  public OME.OMATTR getOMATTR() {
    return omattr;
  }

  /**
   * Gets the value of the omb property.
   * 
   * @return possible object is {@link OMB }
   * 
   */
  public OMB getOMB() {
    return omb;
  }

  /**
   * Gets the value of the ombind property.
   * 
   * @return possible object is {@link OMBIND }
   * 
   */
  public OMBIND getOMBIND() {
    return ombind;
  }

  /**
   * Gets the value of the ome property.
   * 
   * @return possible object is {@link OME }
   * 
   */
  public OME getOME() {
    return ome;
  }

  /**
   * Gets the value of the omf property.
   * 
   * @return possible object is {@link OMF }
   * 
   */
  public OMF getOMF() {
    return omf;
  }

  /**
   * Gets the value of the omi property.
   * 
   * @return possible object is {@link OMI }
   * 
   */
  public OMI getOMI() {
    return omi;
  }

  /**
   * Gets the value of the omr property.
   * 
   * @return possible object is {@link OMR }
   * 
   */
  public OMR getOMR() {
    return omr;
  }

  /**
   * Gets the value of the oms property.
   * 
   * @return possible object is {@link OMS }
   * 
   */
  public OMS getOMS() {
    return oms;
  }

  /**
   * Gets the value of the omstr property.
   * 
   * @return possible object is {@link OMSTR }
   * 
   */
  public OMSTR getOMSTR() {
    return omstr;
  }

  /**
   * Gets the value of the omv property.
   * 
   * @return possible object is {@link OMV }
   * 
   */
  public OMV getOMV() {
    return omv;
  }

  /**
   * Gets the value of the version property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getVersion() {
    return version;
  }

  /**
   * Sets the value of the cdbase property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCdbase(String value) {
    this.cdbase = value;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Sets the value of the oma property.
   * 
   * @param value allowed object is {@link OMA }
   * 
   */
  public void setOMA(OMA value) {
    this.oma = value;
  }

  /**
   * Sets the value of the omattr property.
   * 
   * @param value allowed object is {@link OME.OMATTR }
   * 
   */
  public void setOMATTR(OME.OMATTR value) {
    this.omattr = value;
  }

  /**
   * Sets the value of the omb property.
   * 
   * @param value allowed object is {@link OMB }
   * 
   */
  public void setOMB(OMB value) {
    this.omb = value;
  }

  /**
   * Sets the value of the ombind property.
   * 
   * @param value allowed object is {@link OMBIND }
   * 
   */
  public void setOMBIND(OMBIND value) {
    this.ombind = value;
  }

  /**
   * Sets the value of the ome property.
   * 
   * @param value allowed object is {@link OME }
   * 
   */
  public void setOME(OME value) {
    this.ome = value;
  }

  /**
   * Sets the value of the omf property.
   * 
   * @param value allowed object is {@link OMF }
   * 
   */
  public void setOMF(OMF value) {
    this.omf = value;
  }

  /**
   * Sets the value of the omi property.
   * 
   * @param value allowed object is {@link OMI }
   * 
   */
  public void setOMI(OMI value) {
    this.omi = value;
  }

  /**
   * Sets the value of the omr property.
   * 
   * @param value allowed object is {@link OMR }
   * 
   */
  public void setOMR(OMR value) {
    this.omr = value;
  }

  /**
   * Sets the value of the oms property.
   * 
   * @param value allowed object is {@link OMS }
   * 
   */
  public void setOMS(OMS value) {
    this.oms = value;
  }

  /**
   * Sets the value of the omstr property.
   * 
   * @param value allowed object is {@link OMSTR }
   * 
   */
  public void setOMSTR(OMSTR value) {
    this.omstr = value;
  }

  /**
   * Sets the value of the omv property.
   * 
   * @param value allowed object is {@link OMV }
   * 
   */
  public void setOMV(OMV value) {
    this.omv = value;
  }

  /**
   * Sets the value of the version property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setVersion(String value) {
    this.version = value;
  }

}
