//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2015.06.21 at 11:42:50 PM CEST
//
/**
 * The OMS class was modified! The equal and hash methods were manually added, so that a oms can be compared to another oms.
 * If you recompile this with JAXB please make sure that these methods will be added again.
 */
@javax.xml.bind.annotation.XmlSchema(
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.uni_due.s3.JAXBOpenMath.openmath;
